---
# Jekyll options.
name: Agony Unleashed
domain: https://agony-unleashed.com
baseurl: https://agony-unleashed.com
markdown: redcarpet
highlighter: pygments

# Uncomment below to enable pagination.
# paginate: 5

exclude:
  - CHANGELOG.md
  - LICENSE.txt
  - README.md
  - VERSION
  - Gemfile.lock
  - Gemfile
  - Guardfile
  - Rakefile
  - bower.json
  - bower_components
  - vendor

livereload:
  port: 35729

gems:
  - json
  - jekyll-assets
  - jekyll-assets/compass
  - coffee_script

# Jekyll::AssetsPlugin options.
assets:
  baseurl: https://agony-unleashed.com/assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - bower_components
  compress:
    css: sass
    js: uglifier
  autosize: true

# Use a CDN to load some libraries.
# Libraries are loaded first, asynchronously,
# and should not depend on each other.
cdn_enabled: true
cdn:
  # [ url, loaded check, local asset fallback path ]
  libs:
    - [ "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js", "window.jQuery", "jquery/dist/jquery" ]

# Keywords will be merged with categories, tags, and page keywords.
keywords: [ eve, eve online, pvp, nullsec ]

# Uncomment below to set default meta info.
meta:
  locale: en_US
  description: "EVE Online nullsec PVP specialists. Home of PVP University."
  title:
    prefix: ""
    suffix: " - Agony Unleashed"
  twitter:
    default_card: summary
    site: "@AgonyEmpire"
    creator: "@AgonyEmpire"

# Uncomment below and add your Disqus Shortname to enable Disqus.
# disqus: shortname

# Uncomment below and add your Tracking ID and URL to enable Google Analytics.
# google_analytics:
#   id: UA-00000000-0
#   url: example.com

# Uncomment below and add your Piwik URL to enable Piwik.
# piwik: https://example.com/piwik/

# Uncomment below to enable deploy.
# :deploy:
#   # only :rsync supported
#   :protocol: :rsync
#   # domain name
#   :server: example.com
#   # remote username
#   :user: www
#   # remote port
#   :port: 22
#   # path to remote folder where contents of _site should go
#   # must have trailing slash
#   :path: /var/www/example.com/htdocs/
#   # site files and folders that should be uploaded but not synced
#   # remote content will not be removed from these files and folders
#   :upload_only:
#     - content/

# Foundation Interchange markup support added to
# Jekyll Picture Tag (https://github.com/robwierzbowski/jekyll-picture-tag)
# Uncomment below to enable responsive images.
picture:
  markup: 'interchange'
  source: pictures/fullsize
  output: pictures
  presets:
    default:
      source_retina:
        media: '(retina)'
        width: '1600'
      source_large:
        media: '(large)'
        width: '800'
      source_medium:
        media: '(medium)'
        width: '640'
      source_default:
        width: '640'
    thumb:
      source_large_retina:
        media: '(large_retina)'
        width: '800'
      source_retina:
        media: '(retina)'
        width: '1280'
      source_large:
        media: '(large)'
        width: '400'
      source_medium:
        media: '(medium)'
        width: '640'
      source_default:
        width: '640'
    banner:
      source_xlarge_retina:
        media: '(xlarge_retina)'
        width: '3840'
      source_large_retina:
        media: '(large_retina)'
        width: '2880'
      source_medium_retina:
        media: '(medium_retina)'
        width: '2048'
      source_retina:
        media: '(retina)'
        width: '1280'
      source_xxlarge:
        media: '(xxlarge)'
        width: '2880'
      source_xlarge:
        media: '(xlarge)'
        width: '1920'
      source_large:
        media: '(large)'
        width: '1440'
      source_medium:
        media: '(medium)'
        width: '1024'
      source_default:
        width: '640'

# Uncomment below to configure social media.
# social:
#   facebook:
#     enabled: true
#   google:
#     enabled: true
#     gcfg:
#       lang: en-US
#       parsetags: onload
#   twitter:
#     enabled: true

# Include code from other repos in the final build.
# Each array has the format
# - [ repo, branch, subdirectory, treeish (optional) ]
# Uncomment this example to includes a copy of the gh-pages branch of this repo at
# https://razor-x.github.io/jekyll-and-zurb/inception/jekyll-and-zurb/
# :sub_content:
#   - [ "https://github.com/razor-x/jekyll-and-zurb", gh-pages, inception/jekyll-and-zurb ]
